### ISSUE TITLE
connect.execute types

### ISSUE THREAD

**Issue by hugomrdias** [web3-storage/ucanto#132]
How do i turn `IssuedInvocationView` into a `ServiceInvocation`?

so i can 

```js
const inv1 = invoke({
  capability: cap,
  issuer: this.issuer,
  ...options,
  proofs,
})
const inv2 = invoke({
  capability: cap,
  issuer: this.issuer,
  ...options,
  proofs,
})
connection.execute([inv1, inv2])
```

**Comment by Gozala** [comment]
Hmm I'm not sure what is what here, but isn't this test do exactly what you want ?

https://github.com/web3-storage/ucanto/blob/947e0f3bb1df89b4493fe74a1b26dd889288d11c/packages/client/test/client.spec.js#L220-L226

**Comment by Gozala** [comment]
Oh I think you might be running into the problem because you're doing `connection.execute([inv1, inv2])` as opposed to `connection.execute(inv1, inv2)`

**Comment by Gozala** [comment]
Just to be clear you should not need to cast `IssuedInvocationView` into `ServiceInvocation` because

1. `IssuedInvocationView` view is just an extensions of `IssuedInvocation` (that adds convenience sugar) 

https://github.com/web3-storage/ucanto/blob/947e0f3bb1df89b4493fe74a1b26dd889288d11c/packages/interface/src/lib.ts#L231-L232

2. `ServiceInvocation` in turn is intersection of `IssuedInvocation` with `ServiceInvocations`

https://github.com/web3-storage/ucanto/blob/947e0f3bb1df89b4493fe74a1b26dd889288d11c/packages/interface/src/lib.ts#L144-L147

Which basically means `IssuedInvocation` is fine as long as "service" connection is bound to is compatible has same capabilities. If it is not fine that implies that type service has and type capability has don't align.


For more context this is defined this way to allow creating invocations without tying them to specific connection as thinking was that you could execute same invocation across various connections. That said I think I'd like to have `agent.invoke(...)` API to tie all the things up nicely so these kind of things don't come up.

**Comment by hugomrdias** [comment]
<img width="676" alt="Screen Shot 2022-11-18 at 13 08 09" src="https://user-images.githubusercontent.com/314190/202712397-9a606ece-76b7-4152-b098-eb5732dbacd2.png">

got it to work with args spread but got this error, can we just make it an array of invocations ?

**Comment by Gozala** [comment]
> got it to work with args spread but got this error, can we just make it an array of invocations ?

We could make it a tuple not an array, because otherwise it won't be able to infer the return types. But then execute with one invocation would look kind of odd because you'd have to wrap it in `[]`.

I think error there is because your array may be empty, and execute expects at least one arg.
